// <auto-generated />
using CRUD_Operation.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_Operation.Migrations
{
    [DbContext(typeof(myContext))]
    partial class myContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUD_Operation.Models.User", b =>
                {
                    b.Property<int>("u_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("u_id"));

                    b.Property<string>("EmailOTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("u_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("u_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("u_id");

                    b.HasIndex("u_email")
                        .IsUnique();

                    b.ToTable("tbl_user");
                });
#pragma warning restore 612, 618
        }
    }
}
